GETFILE:
  PRINT "CHOOSE INPUT FILE ([1]=SAMPLE.SEQ [2]=INPUT.SEQ):";
GETKEY:
  GET KEY$: IF KEY$="" THEN GETKEY
  IF KEY$<>"1" AND KEY$<>"2" AND KEY$<>"S" AND KEY$<>"I" AND KEY$<>"Q" THEN GETKEY
  IF KEY$="Q" THEN PRINT "QUIT": END
  IF KEY$="1" OR KEY$="S" THEN FILE$="SAMPLE.SEQ":GOTO GOTFILE
  FILE$="INPUT.SEQ"
GOTFILE:
  PRINT FILE$
  OPEN 1,8,2,FILE$
  OPEN 15,8,15:INPUT#15,DS,DS$,T,S:CLOSE 15
  IF DS THEN CLOSE 1:PRINT DS$:GOTO GETFILE

  DIGIT=0:PART=1
START:
  LEFT = 0
  RIGHT = 1
  DIM WINNERS(9), GOT(24)
  TOTAL = 0
  FOR EOF=0 TO 1 STEP 0
    LINPUT#1, CARD$
REM PRINT "CARD: " CARD$
    EOF = (ST AND 64)/64
    WINNERS.LENGTH = 0
    GOT.LENGTH = 0
    SIDE = LEFT
    GOSUB SKIP.LABEL
    FOR DONE = 0 TO 1 STEP 0
      GOSUB GET.TOKEN
      IF TOKEN$ = "" THEN EXIT.LOOP
      IF VAL(TOKEN$)=0 THEN NOT.DIGIT
      IF SIDE = RIGHT THEN FOUND.NUM
      WINNERS(WINNERS.LENGTH) = VAL(TOKEN$)
      WINNERS.LENGTH = WINNERS.LENGTH + 1
      GOTO NEXT.TOKEN
FOUND.NUM:
      GOT(GOT.LENGTH) = VAL(TOKEN$)
      GOT.LENGTH = GOT.LENGTH + 1
      GOTO NEXT.TOKEN
NOT.DIGIT:
      IF TOKEN$ = "|" THEN SIDE = RIGHT:GOTO NEXT.TOKEN
EXIT.LOOP:
      DONE = 1
NEXT.TOKEN:
    NEXT DONE
    CARD.VALUE = 0
    FOR G = 0 TO GOT.LENGTH - 1
      REM PRINT "CHECKING"GOT(G)
      FOR W = 0 TO WINNERS.LENGTH - 1
        IF GOT(G) <> WINNERS(W) THEN NEXT.NUMBER
        REM PRINT "WINNER!"
        CARD.VALUE = 2 * CARD.VALUE - (CARD.VALUE = 0)
NEXT.NUMBER:
      NEXT W
    NEXT G
    REM PRINT "CARD VALUE:" CARD.VALUE
    TOTAL = TOTAL + CARD.VALUE
  NEXT EOF
  PRINT "TOTAL POINTS:" TOTAL
  END

SKIP.LABEL:
  INDEX = 1
SKIP.TO.COLON:
  CH$ = MID$(CARD$, INDEX, 1)
  INDEX = INDEX + 1
  IF CH$ <> ":" THEN SKIP.TO.COLON
  RETURN

GET.TOKEN:
  CH$ = MID$(CARD$, INDEX, 1)
  INDEX = INDEX + 1
  IF CH$ = " " THEN GET.TOKEN

  TOKEN$ = CH$

TOKEN.CHARS:
  CH$ = MID$(CARD$, INDEX, 1)
  INDEX = INDEX + 1
  IF CH$ <> " " THEN TOKEN$ = TOKEN$ + CH$
  IF CH$ <> " " AND INDEX <= LEN(CARD$) THEN TOKEN.CHARS

  RETURN
