GETFILE:
  PRINT "CHOOSE INPUT FILE ([1]=SAMPLE.SEQ [2]=INPUT.SEQ):";
GETKEY:
  GET KEY$: IF KEY$="" THEN GETKEY
  IF KEY$<>"1" AND KEY$<>"2" AND KEY$<>"S" AND KEY$<>"I" AND KEY$<>"Q" THEN GETKEY
  IF KEY$="Q" THEN PRINT "QUIT": END
  IF KEY$="1" OR KEY$="S" THEN FILE$="SAMPLE.SEQ":GOTO GOTFILE
  FILE$="INPUT.SEQ"
GOTFILE:
  PRINT FILE$
  OPEN 1,8,2,FILE$
  OPEN 15,8,15:INPUT#15,DS,DS$,T,S:CLOSE 15
 

START:
  DIM ROW$(2),COUNTED$(2),PARTNUMS(1)
  TOTAL = 0
  FOR ROW=1 TO 2
    LINPUT#1, ROW$(ROW)
    IF ST AND 64 THEN PRINT "UNEXPECTED EOF": END
  NEXT ROW
  FOR DONE = 0 TO 1 STEP 0
    ROW$(0) = ROW$(1)
    ROW$(1) = ROW$(2)
    IF EOF THEN ROW$(2) = RPT$(46, LEN(ROW$(1))):DONE=1
    IF EOF=0 THEN LINPUT#1, ROW$(2):EOF = (ST AND 64)/64
    MIDDLE$ = ROW$(1)
    FOR I = 1 TO LEN(MIDDLE$)
      CH$ = MID$(MIDDLE$, I, 1)
      IF CH$ <> "*" THEN NEXT.CHAR
      REM RESET COUNTS EVERY PART
      FOR J=0 TO 2
         COUNTED$(J) = RPT$(0, LEN(MIDDLE$))
      NEXT J
      PART.COUNT = 0
      FOR DY = -1 TO 1
        ROW = DY + 1
        TARGET$ = ROW$(ROW)
        FOR DX = -1 TO 1
          IF (DX OR DY) = 0 THEN NEXT.NEIGHBOR
          COL = I + DX
          IF COL < 1 OR COL > LEN(TARGET$) THEN NEXT.NEIGHBOR
          DIGIT$ = MID$(TARGET$, COL, 1)
          IF DIGIT$ < "0" OR DIGIT$ > "9" THEN NEXT.NEIGHBOR
          COUNTED = ASC(MID$(COUNTED$(ROW), COL))
          IF COUNTED THEN NEXT.NEIGHBOR: REM ALREADY COUNTED
          GOSUB GET.PARTNUM
          IF PART.COUNT < 2 THEN PARTNUMS(PART.COUNT) = PARTNUM
          PART.COUNT = PART.COUNT + 1
NEXT.NEIGHBOR:
        NEXT DX
      NEXT DY
      IF PART.COUNT <> 2 THEN NEXT.CHAR
      RATIO = PARTNUMS(0) * PARTNUMS(1)
      TOTAL = TOTAL + RATIO
NEXT.CHAR:
    NEXT I
  NEXT DONE
  PRINT "TOTAL ="TOTAL
  END

GET.PARTNUM:
  REM FOUND A DIGIT THAT WE SHOULD COUNT. FIND THE NUMBER CONTAINING IT AND ADD IT TO THE TOTAL
  LEFT = COL
  RIGHT = COL
  FIRST = 0
  LAST = 0
  FOR GP.DONE = 0 TO -1 STEP 0
    IF FIRST THEN DO.RIGHT
    IF LEFT=1 THEN FIRST=LEFT: GOTO DO.RIGHT
    DIGIT$ = MID$(ROW$(ROW), LEFT-1, 1)
    IF DIGIT$ < "0" OR DIGIT$ > "9" THEN FIRST=LEFT:GOTO DO.RIGHT
    LEFT = LEFT - 1
DO.RIGHT:
    IF LAST THEN NEXT.SCAN
    IF RIGHT=LEN(ROW$(ROW)) THEN LAST=RIGHT: GOTO NEXT.SCAN
    DIGIT$ = MID$(ROW$(ROW), RIGHT+1, 1)
    IF DIGIT$ < "0" OR DIGIT$ > "9" THEN LAST=RIGHT:GOTO NEXT.SCAN
    RIGHT = RIGHT + 1
NEXT.SCAN:
    GP.DONE = (FIRST > 0)  AND (LAST > 0)
  NEXT GP.DONE
  SIZE = LAST - FIRST + 1
  PARTNUM = VAL(MID$(ROW$(ROW),FIRST,SIZE))
  COUNTED$(ROW) = LEFT$(COUNTED$(ROW), FIRST - 1) + RPT$(1, SIZE) + MID$(COUNTED$(ROW), LAST + 1)
  RETURN
