GETFILE:
  PRINT "CHOOSE INPUT FILE ([1]=SAMPLE.SEQ [2]=INPUT.SEQ):";
GETKEY:
  GET KEY$: IF KEY$="" THEN GETKEY
  IF KEY$<>"1" AND KEY$<>"2" AND KEY$<>"S" AND KEY$<>"I" AND KEY$<>"Q" THEN GETKEY
  IF KEY$="Q" THEN PRINT "QUIT": END
  IF KEY$="1" OR KEY$="S" THEN FILE$="SAMPLE.SEQ":GOTO GOTFILE
  FILE$="INPUT.SEQ"
GOTFILE:
  PRINT FILE$
  OPEN 1,8,2,FILE$
  OPEN 15,8,15:INPUT#15,DS,DS$,T,S:CLOSE 15
  IF DS THEN CLOSE 1:PRINT DS$:GOTO GETFILE

START:
  DIM ROW$(1),COUNTED$(1):CUR=0
  TOTAL = 0
  FOR EOF=0 TO 1 STEP 0
    LINPUT#1, ROW$(CUR)
    EOF = (ST AND 64) / 64
    PREV = 1 - CUR
    REM HAVEN'T COUNTED ANY OF THIS YET
    COUNTED$(CUR) = RPT$(0, LEN(ROW$(CUR)))
    FOR I=1 TO LEN(ROW$(CUR))
      CH$=MID$(ROW$(CUR),I,1)
      IF CH$="." OR (CH$ >= "0" AND CH$ <= "9") THEN NEXT.CHAR
      REM FOUND A PART
      DO.VERTICAL = LEN(ROW$(PREV)) > 0
      FOR DX = -1 TO 1
        NI = I + DX
        IF NI < 1 OR NI > LEN(ROW$(CUR)) THEN NEXT.NEIGHBOR
        FOR DY=DO.VERTICAL TO 0
          IF NOT (DX OR DY) THEN NEXT.NEIGHBOR
          ROW = CUR + DY
          IF MID$(COUNTED$(ROW), NI, 1) THEN NEXT.NEIGHBOR
          DIGIT$ = MID$(ROW$(ROW), NI, 1)
          IF DIGIT$ < "0" OR DIGIT$ > "9" THEN NEXT.NEIGHBOR
          REM FOUND A DIGIT
          LEFT = NI
          RIGHT = NI
          FIRST = 0
          LAST = 0
          FOR DONE = 0 TO 1 STEP 0
            IF FIRST THEN DO.RIGHT
            IF LEFT=1 THEN FIRST=LEFT: GOTO DO.RIGHT
            DIGIT$ = MID$(ROW$(ROW), LEFT-1, 1)
            IF DIGIT$ < "0" OR DIGIT$ > "9" THEN FIRST=LEFT:GOTO DO.RIGHT
            LEFT = LEFT - 1
DO.RIGHT:
            IF LAST THEN NEXT.SCAN
            IF RIGHT=LEN(ROW$(ROW)) THEN LAST=RIGHT: GOTO NEXT.SCAN
            DIGIT$ = MID$(ROW$(ROW), RIGHT+1, 1)
            IF DIGIT$ < "0" OR DIGIT$ > "9" THEN LAST=RIGHT:GOTO NEXT.SCAN
            RIGHT = RIGHT + 1
NEXT.SCAN:
            DONE = FIRST AND LAST
          NEXT DONE
          SIZE = LAST - FIRST + 1
          VALUE = VAL(MID$(ROW$(ROW),FIRST,SIZE)
          PRINT "ADDING"VALUE
          TOTAL = TOTAL + VALUE
          COUNTED$(ROW) = LEFT$(COUNTED$(ROW), FIRST - 1) + RPT$(1, SIZE) + MID$(COUNTED$(ROW), LAST + 1)
NEXT.NEIGHBOR:
        NEXT DY
      NEXT DX
NEXT.CHAR:
    NEXT I
    CUR = 1 - CUR
  NEXT EOF
  PRINT "TOTAL:"TOTAL
