GETFILE:
  PRINT "ENTER FILENAME: INPUT.SEQ";
  PRINT RPT$(157,9);:
  OPEN 1,0:INPUT#1,FI$:CLOSE 1:PRINT:TI=0
  OPEN 1,8,2,FI$
  OPEN 15,8,15:INPUT#15,DS,DS$,T,S:CLOSE 15
  IF DS THEN PRINT DS$:GOTO GETFILE

  RED = 12 : GREEN = 13 : BLUE = 14
  TOTAL = 0
  FOR EOF=0 TO 1 STEP 0
    LINPUT#1, LI$
    EOF = (ST AND 64) / 64
    GAME = GAME + 1
    OK = 1
    GOSUB INITLINE
GETPLAY:
    GOSUB READPLAY
    REM PRINT "GAME"GAME":R="R",G="G",B="B
    IF R < 0 THEN DONE
    IF R > RED OR G > GREEN OR B > BLUE THEN OK=0: GOTO NEXTLINE
    GOTO GETPLAY
DONE:
    IF OK THEN TOTAL = TOTAL + GAME
NEXTLINE:
  NEXT EOF

  PRINT TOTAL
  PRINT TI
  END

INITLINE:
  LI$ = LI$ + ";"
  INDEX = 1
SKIP:
  CH$ = MID$(LI$,INDEX,1)
  INDEX = INDEX + 1
  IF CH$<>":" THEN SKIP
  RETURN

READPLAY:
  R = -1
  G = 0 : B = 0
  TALLY = 0

PARSE:
  IF INDEX > LEN(LI$) THEN RETURN
  CH$ = MID$(LI$, INDEX, 1)
  INDEX = INDEX + 1
  IF CH$ = ";" THEN RETURN
  IF R=-1 THEN R=0
  IF CH$ = " " THEN PARSE
  IF CH$ >= "0" AND CH$ <= "9" THEN TALLY = TALLY * 10 + VAL(CH$):GOTO PARSE
  IF CH$ = "B" THEN B=TALLY:TALLY=0: GOTO WORD
  IF CH$ = "G" THEN G=TALLY:TALLY=0: GOTO WORD
  IF CH$ = "R" THEN R=TALLY:TALLY=0: GOTO WORD
  PRINT "ERROR PARSING GAME"GAME
  END
WORD:
  CH$ = MID$(LI$, INDEX, 1)
  INDEX = INDEX + 1
  IF CH$<>"," AND CH$<>";" THEN WORD
  IF CH$=";" THEN RETURN
  GOTO PARSE
